"""100 meters"""
r1 = float(input())
r2 = float(input())
r3 = float(input())
r4 = float(input())
r5 = float(input())
r6 = float(input())
r7 = float(input())
r8 = float(input())

FIRST_TIME = r1
FIRST_RUNNER = 1
SECOND_TIME = None
SECOND_RUNNER = None
THIRD_TIME = None
BRONZE_RUNNER = None

if r2 < FIRST_TIME:
    SECOND_TIME, SECOND_RUNNER = FIRST_TIME, FIRST_RUNNER
    FIRST_TIME, FIRST_RUNNER = r2, 2
else:
    SECOND_TIME, SECOND_RUNNER = r2, 2

if r3 < FIRST_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = FIRST_TIME, FIRST_RUNNER
    FIRST_TIME, FIRST_RUNNER = r3, 3
elif r3 < SECOND_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = r3, 3
else:
    THIRD_TIME, BRONZE_RUNNER = r3, 3

if r4 < FIRST_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = FIRST_TIME, FIRST_RUNNER
    FIRST_TIME, FIRST_RUNNER = r4, 4
elif r4 < SECOND_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = r4, 4
elif r4 < THIRD_TIME:
    THIRD_TIME, BRONZE_RUNNER = r4, 4

if r5 < FIRST_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = FIRST_TIME, FIRST_RUNNER
    FIRST_TIME, FIRST_RUNNER = r5, 5
elif r5 < SECOND_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = r5, 5
elif r5 < THIRD_TIME:
    THIRD_TIME, BRONZE_RUNNER = r5, 5

if r6 < FIRST_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = FIRST_TIME, FIRST_RUNNER
    FIRST_TIME, FIRST_RUNNER = r6, 6
elif r6 < SECOND_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = r6, 6
elif r6 < THIRD_TIME:
    THIRD_TIME, BRONZE_RUNNER = r6, 6

if r7 < FIRST_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = FIRST_TIME, FIRST_RUNNER
    FIRST_TIME, FIRST_RUNNER = r7, 7
elif r7 < SECOND_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = r7, 7
elif r7 < THIRD_TIME:
    THIRD_TIME, BRONZE_RUNNER = r7, 7

if r8 < FIRST_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = FIRST_TIME, FIRST_RUNNER
    FIRST_TIME, FIRST_RUNNER = r8, 8
elif r8 < SECOND_TIME:
    THIRD_TIME, BRONZE_RUNNER = SECOND_TIME, SECOND_RUNNER
    SECOND_TIME, SECOND_RUNNER = r8, 8
elif r8 < THIRD_TIME:
    THIRD_TIME, BRONZE_RUNNER = r8, 8
print(FIRST_RUNNER, SECOND_RUNNER, BRONZE_RUNNER)
